# Site settings
title: Alexander Bell-Towne's Blog
email: blog@bell-towne.com
description: >-
  This is a blog I am writing.
twitter_username: alexbbt
github_username: alexbbt

permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
